"""empty message

Revision ID: 14959217f4ef
Revises: 587a454810ce
Create Date: 2015-08-10 10:57:58.261668

"""

# revision identifiers, used by Alembic.
revision = '14959217f4ef'
down_revision = '587a454810ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
