"""empty message

Revision ID: 1646e58b1ed2
Revises: 14959217f4ef
Create Date: 2015-11-04 11:05:16.520660

"""

# revision identifiers, used by Alembic.
revision = '1646e58b1ed2'
down_revision = '14959217f4ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
